name: Release
on:
  push:
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/checkout@v5
        with:
          repository: "pgroonga/pgroonga.github.io"
          path: "pgroonga.github.io"
      - name: Extract release note
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ruby \
            -e 'print("## PGroonga "); \
                puts(ARGF.read.split(/^## /)[1]. \
                       gsub(/ {.+?}/, ""). \
                       gsub(/\[(.+?)\]\[.+?\]/) {$1})' \
            pgroonga.github.io/news/index.md | tee release-note.md

          previous_tag=$(gh release list \
                           --jq '.[].tagName' \
                           --json tagName \
                           --limit 1)

          echo "### Contributors" | tee -a release-note.md
          echo | tee -a release-note.md
          command_line="git shortlog -sn ${previous_tag}.."
          echo '```console' | tee -a release-note.md
          echo "\$ ${command_line}" | tee -a release-note.md
          ${command_line} | tee -a release-note.md
          echo '```' | tee -a release-note.md
          pwd
          ls -al
      - name: Download artifacts
        run: |
          run_id=18032601008
          gh run download ${run_id} \
          --dir release-artifacts \
          --pattern "release-*" \
          --repo ${GITHUB_REPOSITORY}
          pwd
          ls -al
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Publish
        run: |
          title=$(head -n1 release-note.md | sed -e 's/^## //')
          tail -n +2 release-note.md > release-note-without-version.md
          pwd
          ls -al
          ls -al release-artifacts/
        env:
          GH_TOKEN: ${{ github.token }}
